# Generated by Django 5.2 on 2025-04-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sensorreading_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorreading',
            options={},
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
