# Generated by Django 5.2 on 2025-04-08 23:28

import app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_sensorreading_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lampi',
            fields=[
                ('name', models.CharField(default='My LAMPI', max_length=50)),
                ('device_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('association_code', models.CharField(default=app.models.generate_association_code, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=models.SET(app.models.get_parked_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
