# Generated by Django 5.2 on 2025-04-09 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_lampi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='user',
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='lampi',
            field=models.ForeignKey(default='b827eb761867', on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='app.lampi'),
            preserve_default=False,
        ),
    ]
