# Generated by Django 5.2 on 2025-04-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_sensorreading_user_sensorreading_lampi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='altitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
